export const countries = [
  { name: "Brasil", code: "BR", dialCode: "+55", flag: "🇧🇷" },
  { name: "Portugal", code: "PT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Estados Unidos", code: "US", dialCode: "+1", flag: "🇺🇸" },
  { name: "Canadá", code: "CA", dialCode: "+1", flag: "🇨🇦" },
  { name: "Angola", code: "AO", dialCode: "+244", flag: "🇦🇴" },
  { name: "Moçambique", code: "MZ", dialCode: "+258", flag: "🇲🇿" },
  { name: "Argentina", code: "AR", dialCode: "+54", flag: "🇦🇷" },
  { name: "Uruguai", code: "UY", dialCode: "+598", flag: "🇺🇾" },
  { name: "Paraguai", code: "PY", dialCode: "+595", flag: "🇵🇾" },
  { name: "Chile", code: "CL", dialCode: "+56", flag: "🇨🇱" },
  { name: "Colômbia", code: "CO", dialCode: "+57", flag: "🇨🇴" },
  { name: "Espanha", code: "ES", dialCode: "+34", flag: "🇪🇸" },
  { name: "Reino Unido", code: "GB", dialCode: "+44", flag: "🇬🇧" },
  { name: "França", code: "FR", dialCode: "+33", flag: "🇫🇷" },
  { name: "Itália", code: "IT", dialCode: "+39", flag: "🇮🇹" },
  { name: "Alemanha", code: "DE", dialCode: "+49", flag: "🇩🇪" },
  { name: "Japão", code: "JP", dialCode: "+81", flag: "🇯🇵" },
  { name: "China", code: "CN", dialCode: "+86", flag: "🇨🇳" },
  { name: "Índia", code: "IN", dialCode: "+91", flag: "🇮🇳" },
  { name: "México", code: "MX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Austrália", code: "AU", dialCode: "+61", flag: "🇦🇺" },
  { name: "Peru", code: "PE", dialCode: "+51", flag: "🇵🇪" },
  { name: "Bolívia", code: "BO", dialCode: "+591", flag: "🇧🇴" },
  { name: "Venezuela", code: "VE", dialCode: "+58", flag: "🇻🇪" },
];
