/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as PlanosAlbertRouteImport } from './routes/planos-albert'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ObrigadoCorretorRouteImport } from './routes/obrigado-corretor'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as DiaCorretorRouteImport } from './routes/dia-corretor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolucoesIndexRouteImport } from './routes/solucoes.index'
import { Route as MateriaisIndexRouteImport } from './routes/materiais.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolucoesSlugRouteImport } from './routes/solucoes.$slug'
import { Route as MateriaisSlugRouteImport } from './routes/materiais.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosAlbertRoute = PlanosAlbertRouteImport.update({
  id: '/planos-albert',
  path: '/planos-albert',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoCorretorRoute = ObrigadoCorretorRouteImport.update({
  id: '/obrigado-corretor',
  path: '/obrigado-corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaCorretorRoute = DiaCorretorRouteImport.update({
  id: '/dia-corretor',
  path: '/dia-corretor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesIndexRoute = SolucoesIndexRouteImport.update({
  id: '/solucoes/',
  path: '/solucoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisIndexRoute = MateriaisIndexRouteImport.update({
  id: '/materiais/',
  path: '/materiais/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolucoesSlugRoute = SolucoesSlugRouteImport.update({
  id: '/solucoes/$slug',
  path: '/solucoes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisSlugRoute = MateriaisSlugRouteImport.update({
  id: '/materiais/$slug',
  path: '/materiais/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dia-corretor': typeof DiaCorretorRoute
  '/empresa': typeof EmpresaRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado-corretor': typeof ObrigadoCorretorRoute
  '/planos': typeof PlanosRoute
  '/planos-albert': typeof PlanosAlbertRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/materiais/$slug': typeof MateriaisSlugRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/materiais/': typeof MateriaisIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dia-corretor': typeof DiaCorretorRoute
  '/empresa': typeof EmpresaRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado-corretor': typeof ObrigadoCorretorRoute
  '/planos': typeof PlanosRoute
  '/planos-albert': typeof PlanosAlbertRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/materiais/$slug': typeof MateriaisSlugRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/materiais': typeof MateriaisIndexRoute
  '/solucoes': typeof SolucoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dia-corretor': typeof DiaCorretorRoute
  '/empresa': typeof EmpresaRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado-corretor': typeof ObrigadoCorretorRoute
  '/planos': typeof PlanosRoute
  '/planos-albert': typeof PlanosAlbertRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/materiais/$slug': typeof MateriaisSlugRoute
  '/solucoes/$slug': typeof SolucoesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/materiais/': typeof MateriaisIndexRoute
  '/solucoes/': typeof SolucoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dia-corretor'
    | '/empresa'
    | '/obrigado'
    | '/obrigado-corretor'
    | '/planos'
    | '/planos-albert'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/blog/$slug'
    | '/materiais/$slug'
    | '/solucoes/$slug'
    | '/blog/'
    | '/materiais/'
    | '/solucoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dia-corretor'
    | '/empresa'
    | '/obrigado'
    | '/obrigado-corretor'
    | '/planos'
    | '/planos-albert'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/blog/$slug'
    | '/materiais/$slug'
    | '/solucoes/$slug'
    | '/blog'
    | '/materiais'
    | '/solucoes'
  id:
    | '__root__'
    | '/'
    | '/dia-corretor'
    | '/empresa'
    | '/obrigado'
    | '/obrigado-corretor'
    | '/planos'
    | '/planos-albert'
    | '/politica-de-cookies'
    | '/politica-de-privacidade'
    | '/blog/$slug'
    | '/materiais/$slug'
    | '/solucoes/$slug'
    | '/blog/'
    | '/materiais/'
    | '/solucoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiaCorretorRoute: typeof DiaCorretorRoute
  EmpresaRoute: typeof EmpresaRoute
  ObrigadoRoute: typeof ObrigadoRoute
  ObrigadoCorretorRoute: typeof ObrigadoCorretorRoute
  PlanosRoute: typeof PlanosRoute
  PlanosAlbertRoute: typeof PlanosAlbertRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MateriaisSlugRoute: typeof MateriaisSlugRoute
  SolucoesSlugRoute: typeof SolucoesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MateriaisIndexRoute: typeof MateriaisIndexRoute
  SolucoesIndexRoute: typeof SolucoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos-albert': {
      id: '/planos-albert'
      path: '/planos-albert'
      fullPath: '/planos-albert'
      preLoaderRoute: typeof PlanosAlbertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado-corretor': {
      id: '/obrigado-corretor'
      path: '/obrigado-corretor'
      fullPath: '/obrigado-corretor'
      preLoaderRoute: typeof ObrigadoCorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dia-corretor': {
      id: '/dia-corretor'
      path: '/dia-corretor'
      fullPath: '/dia-corretor'
      preLoaderRoute: typeof DiaCorretorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/': {
      id: '/solucoes/'
      path: '/solucoes'
      fullPath: '/solucoes/'
      preLoaderRoute: typeof SolucoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais/': {
      id: '/materiais/'
      path: '/materiais'
      fullPath: '/materiais/'
      preLoaderRoute: typeof MateriaisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solucoes/$slug': {
      id: '/solucoes/$slug'
      path: '/solucoes/$slug'
      fullPath: '/solucoes/$slug'
      preLoaderRoute: typeof SolucoesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais/$slug': {
      id: '/materiais/$slug'
      path: '/materiais/$slug'
      fullPath: '/materiais/$slug'
      preLoaderRoute: typeof MateriaisSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiaCorretorRoute: DiaCorretorRoute,
  EmpresaRoute: EmpresaRoute,
  ObrigadoRoute: ObrigadoRoute,
  ObrigadoCorretorRoute: ObrigadoCorretorRoute,
  PlanosRoute: PlanosRoute,
  PlanosAlbertRoute: PlanosAlbertRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  BlogSlugRoute: BlogSlugRoute,
  MateriaisSlugRoute: MateriaisSlugRoute,
  SolucoesSlugRoute: SolucoesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  MateriaisIndexRoute: MateriaisIndexRoute,
  SolucoesIndexRoute: SolucoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
